#ifndef ING1_PROJET_2021_22_DOFUS_ARENA_TEAM_AA_SORTS_H
#define ING1_PROJET_2021_22_DOFUS_ARENA_TEAM_AA_SORTS_H


typedef struct{
    int porteeX;
    int porteeY;
}Sort;

#endif //ING1_PROJET_2021_22_DOFUS_ARENA_TEAM_AA_SORTS_H
